### ISSUE TITLE
Why not add a Readme? Would be easier to understand what's going on.

### ISSUE THREAD

**Issue by aurtistictrader** [m26jiang/LeHeartsClient#3]

**Comment by m26jiang** [comment]
ychug

**Comment by Hextortion** [comment]
What exactly should be included in the Readme?

**Comment by m26jiang** [comment]
nothing.... There's nothing going on with this program.
Stfu and I understand what's going on perfectly

**Comment by Hextortion** [comment]
If you want a readme to be created, I'm not sure if you want to know how the code works, or how to use the client or what.

**Comment by aurtistictrader** [comment]
Probably how to use theclient. I want to usethe client to test the server. Especially when I add new features to theservers.

**Comment by m26jiang** [comment]
It's an application.... You run the jar file then you're done :S

**Comment by aurtistictrader** [comment]
Let's say I am in the process of adding a feature on the server. I want to to test it with the client, but the command isn't being handled yet.  I would haveto add a rudimentary handler.

**Comment by m26jiang** [comment]
nut yo jawb. just open an issue

**Comment by Hextortion** [comment]
Yeah, I'm just saying... The client is not really ready to be used for testing. GUI is nowhere close to being ready, and any time you implement new features, we would have to add support for it as well.
